//
// Created by andre on 10-06-2023.
//

#ifndef CINEMAAPPLICATION_INSUFICCIENTCASHEXCEPTION_H
#define CINEMAAPPLICATION_INSUFICCIENTCASHEXCEPTION_H

#endif //CINEMAAPPLICATION_INSUFICCIENTCASHEXCEPTION_H
