//
// Created by andre on 10-06-2023.
//

#ifndef CINEMAAPPLICATION_INSUFFICIENTCASHEXCEPTION_H
#define CINEMAAPPLICATION_INSUFFICIENTCASHEXCEPTION_H

#endif //CINEMAAPPLICATION_INSUFFICIENTCASHEXCEPTION_H
