//
// Created by andre on 10-06-2023.
//

#ifndef CINEMAAPPLICATION_ROOMALREADYFULLEXCEPTION_H
#define CINEMAAPPLICATION_ROOMALREADYFULLEXCEPTION_H

#endif //CINEMAAPPLICATION_ROOMALREADYFULLEXCEPTION_H
