//
// Created by andre on 10-06-2023.
//

#ifndef CINEMAAPPLICATION_SEATNOLONGERAVAILABLEEXCEPTION_H
#define CINEMAAPPLICATION_SEATNOLONGERAVAILABLEEXCEPTION_H

#endif //CINEMAAPPLICATION_SEATNOLONGERAVAILABLEEXCEPTION_H
